services:
  - type: web
    name: crud-planner-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MS_GRAPH_CLIENT_ID
        sync: false
      - key: MS_GRAPH_TENANT_ID
        sync: false
      - key: MS_GRAPH_CLIENT_SECRET
        sync: false
      - key: DATABASE_URL
        value: sqlite:///./planner.db
